# -*- coding: utf-8 -*-
# CompanyFlow Solutions data. Edit TEXT here, never in the generated HTML.
CATS = [
 ("Development", [
  ("custom-business-software","Custom Business Software","Custom web apps to transform businesses"),
  ("business-management-systems","Business Management Systems","Expert software solutions for every operation"),
  ("websites-landing-pages","Websites & Landing Pages","Stunning websites that drive engagement"),
  ("ai-automation","AI Automation","Intelligent automation that streamlines your work"),
  ("mobile-web-apps","Mobile & Web Apps","Customised mobile apps for every platform")]),
 ("Design", [
  ("ui-ux-product-design","UI/UX & Product Design","Creating a unique identity for your business"),
  ("ecommerce-development","Ecommerce Development","Online stores built to sell and scale"),
  ("conversion-focused-landing-pages","Conversion-Focused Landing Pages","Landing pages designed to convert visitors"),
  ("product-ui-ux","Product UI/UX","Intuitive designs for user satisfaction"),
  ("creative-digital-experiences","Creative Digital Experiences","Creative visuals to captivate your audience")]),
 ("Digital Marketing", [
  ("lead-generation","Lead Generation","Targeted campaigns for maximum reach"),
  ("digital-growth","Digital Growth","Grow your brand across digital channels"),
  ("analytics-tracking","Analytics & Tracking","Data insights for smarter decisions"),
  ("performance-marketing","Performance Marketing","Strategic ads for higher conversions"),
  ("content-systems","Content Systems","Content that keeps customers engaged")]),
 ("Automation", [
  ("workflow-automation","Workflow Automation","Automate repetitive tasks to boost efficiency and accuracy"),
  ("ai-solutions","AI Solutions","Enable systems to learn and improve with AI-driven algorithms"),
  ("ai-sales-agents","AI Sales Agents","Enhance customer interactions with intelligent virtual assistants"),
  ("business-intelligence","Business Intelligence","Extract valuable insights from complex data for better decisions")]),
 ("Cyber Security", [
  ("secure-business-systems","Secure Business Systems","Safeguard devices from cyber threats, malware and breaches"),
  ("cloud-infrastructure","Cloud Infrastructure","Protect cloud data and systems with advanced security tools"),
  ("reliable-backups","Reliable Backups","Ensure seamless recovery from unexpected data loss or attacks"),
  ("authentication-access","Authentication & Access","Strengthen identity protection with multi-layered access controls"),
  ("application-hardening","Application Hardening","Defend apps against vulnerabilities during and after deployment"),
  ("security-reviews","Security Reviews","Analyze and enhance your organization's complete security framework")]),
 ("Other", [
  ("website-content","Website Content","Creating engaging and informative content"),
  ("seo","SEO","Effective SEO strategies to increase traffic"),
  ("documentation-training","Documentation & Training","Learn and grow with expert-led training programs"),
  ("domain-hosting","Domain & Hosting","Trusted hosting for your online presence"),
  ("technical-documentation","Technical Documentation","Boost credibility with clear technical documentation")]),
]

def T(*pairs): return [(a,b) for a,b in pairs]
TECH = {
 "web": {"Frontend":[("React","react"),("Angular","angularjs"),("Vue.js","vuejs"),("Next.js","nextjs"),("HTML5","html5"),("CSS3","css3"),("JavaScript","javascript"),("TypeScript","typescript"),("Tailwind","tailwindcss"),("Bootstrap","bootstrap")],
         "Backend":[("Node.js","nodejs"),("PHP","php"),("Java","java"),("Python","python"),(".NET","dotnetcore"),("C#","csharp"),("Go","go"),("Ruby","ruby")],
         "Database":[("MySQL","mysql"),("PostgreSQL","postgresql"),("MongoDB","mongodb"),("Redis","redis"),("Firebase","firebase"),("SQL Server","microsoftsqlserver"),("SQLite","sqlite"),("Oracle","oracle")],
         "Framework":[("Laravel","laravel"),("Django","django"),("Flask","flask"),("Express","express"),("Spring","spring"),("Rails","rails"),("ASP.NET","dotnetcore"),("NestJS","nestjs")]},
 "mobile": {"Languages":[("Kotlin","kotlin"),("Swift","swift"),("Dart","dart"),("Java","java"),("JavaScript","javascript"),("TypeScript","typescript"),("C#","csharp"),("Objective-C","objectivec")],
            "Framework":[("Flutter","flutter"),("React Native","react"),("Ionic","ionic"),("Xamarin","xamarin"),("Android","android"),("iOS","apple")],
            "Database":[("Firebase","firebase"),("Node.js","nodejs"),("PostgreSQL","postgresql"),("MongoDB","mongodb"),("MySQL","mysql"),("Redis","redis")],
            "Tools":[("Android Studio","androidstudio"),("Xcode","xcode"),("Figma","figma"),("Git","git"),("Postman","postman"),("Jira","jira")]},
 "design": {"Design":[("Figma","figma"),("Adobe XD","xd"),("Photoshop","photoshop"),("Illustrator","illustrator"),("Sketch","sketch"),("InDesign","indesign"),("After Effects","aftereffects"),("Premiere Pro","premierepro")],
            "Prototype":[("Figma","figma"),("Adobe XD","xd"),("InVision","invision"),("Zeplin","zeplin"),("Miro","miro"),("Notion","notion")],
            "Build":[("HTML5","html5"),("CSS3","css3"),("JavaScript","javascript"),("React","react"),("Tailwind","tailwindcss"),("Bootstrap","bootstrap"),("Sass","sass")],
            "Platforms":[("WordPress","wordpress"),("WooCommerce","woocommerce"),("Shopify","shopify"),("Magento","magento"),("Webflow","webflow"),("PHP","php")]},
 "ecom": {"Platforms":[("Shopify","shopify"),("WooCommerce","woocommerce"),("Magento","magento"),("WordPress","wordpress"),("BigCommerce","bigcommerce"),("Webflow","webflow")],
          "Frontend":[("React","react"),("Next.js","nextjs"),("Vue.js","vuejs"),("HTML5","html5"),("CSS3","css3"),("JavaScript","javascript"),("Tailwind","tailwindcss"),("Bootstrap","bootstrap")],
          "Backend":[("Node.js","nodejs"),("PHP","php"),("Laravel","laravel"),("Python","python"),("MySQL","mysql"),("PostgreSQL","postgresql"),("Redis","redis")],
          "Payments":[("Stripe","stripe"),("PayPal","paypal"),("Google Pay","google"),("Apple Pay","apple"),("Razorpay","razorpay"),("JazzCash","jazzcash")]},
 "marketing": {"Analytics":[("Google Analytics","googleanalytics"),("Tag Manager","googletagmanager"),("Looker Studio","looker"),("Hotjar","hotjar"),("Mixpanel","mixpanel"),("Power BI","powerbi")],
               "Advertising":[("Google Ads","google"),("Meta Ads","facebook"),("LinkedIn Ads","linkedin"),("TikTok Ads","tiktok"),("YouTube","youtube"),("X Ads","twitter")],
               "Email & CRM":[("HubSpot","hubspot"),("Mailchimp","mailchimp"),("Zoho","zoho"),("Salesforce","salesforce"),("Klaviyo","klaviyo"),("WhatsApp","whatsapp")],
               "SEO":[("Search Console","google"),("Semrush","semrush"),("Ahrefs","ahrefs"),("Screaming Frog","screamingfrog"),("WordPress","wordpress"),("Yoast","yoast")]},
 "automation": {"AI & ML":[("Python","python"),("TensorFlow","tensorflow"),("PyTorch","pytorch"),("OpenAI","openai"),("Jupyter","jupyter"),("scikit-learn","scikitlearn"),("Hugging Face","huggingface")],
                "Automation":[("n8n","n8n"),("Zapier","zapier"),("Make","make"),("Selenium","selenium"),("UiPath","uipath"),("Power Automate","powerautomate")],
                "Data":[("PostgreSQL","postgresql"),("MongoDB","mongodb"),("Redis","redis"),("Pandas","pandas"),("NumPy","numpy"),("Power BI","powerbi"),("Grafana","grafana")],
                "Integrations":[("WhatsApp","whatsapp"),("Slack","slack"),("Google","google"),("Notion","notion"),("Node.js","nodejs"),("Docker","docker")]},
 "security": {"Cloud":[("AWS","amazonwebservices"),("Azure","azure"),("Google Cloud","googlecloud"),("DigitalOcean","digitalocean"),("Cloudflare","cloudflare"),("Docker","docker"),("Kubernetes","kubernetes")],
              "Infrastructure":[("Linux","linux"),("Nginx","nginx"),("Apache","apache"),("Terraform","terraform"),("Jenkins","jenkins"),("GitHub","github"),("GitLab","gitlab")],
              "Identity":[("OAuth","oauth"),("Auth0","auth0"),("Okta","okta"),("Keycloak","keycloak"),("Firebase","firebase"),("JWT","jwt")],
              "Monitoring":[("Grafana","grafana"),("Prometheus","prometheus"),("Elastic","elasticsearch"),("Sentry","sentry"),("Datadog","datadog"),("Wireshark","wireshark")]},
 "other": {"CMS":[("WordPress","wordpress"),("Webflow","webflow"),("Drupal","drupal"),("Joomla","joomla"),("Ghost","ghost"),("Strapi","strapi")],
           "SEO":[("Search Console","google"),("Semrush","semrush"),("Ahrefs","ahrefs"),("Screaming Frog","screamingfrog"),("Google Analytics","googleanalytics"),("Yoast","yoast")],
           "Hosting":[("AWS","amazonwebservices"),("Cloudflare","cloudflare"),("DigitalOcean","digitalocean"),("Vercel","vercel"),("Netlify","netlify"),("Nginx","nginx"),("Linux","linux")],
           "Docs":[("Notion","notion"),("Confluence","confluence"),("Markdown","markdown"),("GitHub","github"),("Figma","figma"),("Google Docs","google")]},
}
PRESET = {"custom-business-software":"web","business-management-systems":"web","websites-landing-pages":"web","ai-automation":"automation","mobile-web-apps":"mobile",
 "ui-ux-product-design":"design","ecommerce-development":"ecom","conversion-focused-landing-pages":"design","product-ui-ux":"design","creative-digital-experiences":"design",
 "lead-generation":"marketing","digital-growth":"marketing","analytics-tracking":"marketing","performance-marketing":"marketing","content-systems":"other",
 "workflow-automation":"automation","ai-solutions":"automation","ai-sales-agents":"automation","business-intelligence":"automation",
 "secure-business-systems":"security","cloud-infrastructure":"security","reliable-backups":"security","authentication-access":"security","application-hardening":"security","security-reviews":"security",
 "website-content":"other","seo":"other","documentation-training":"other","domain-hosting":"other","technical-documentation":"other"}
GLYPH = {"Development":"code","Design":"pen","Digital Marketing":"chart","Automation":"gear","Cyber Security":"shield","Other":"doc"}



# Service-page copy used by the CompanyFlow solutions builder.
P = {
    "custom-business-software": ("Custom Business Software", "Custom web apps to transform businesses. We combine thoughtful strategy, proven technology and clear communication to deliver a solution that fits the way your business works.", "Connect Now", "A practical approach to custom business software", "CompanyFlow plans, builds and supports custom business software around your goals. We focus on dependable delivery, clear milestones and measurable business outcomes—not unnecessary complexity.", ("Business-focused delivery", "Reliable ongoing support"), [("Strategy & Planning", "We define goals, scope and a realistic roadmap before implementation."), ("Custom Implementation", "A solution shaped around your workflows, systems and customers."), ("Quality & Testing", "We check usability, performance and reliability before launch."), ("Continuous Improvement", "We help your solution evolve as your business grows.")], [("What is included in Custom Business Software?", "The scope is tailored to your goals and may include discovery, planning, implementation, testing and launch support."), ("Can this work with our existing systems?", "Yes. We review your current tools first and plan integrations where they add value.")], ("70+", 5)),
    "business-management-systems": ("Business Management Systems", "Expert software solutions for every operation. We combine thoughtful strategy, proven technology and clear communication to deliver a solution that fits the way your business works.", "Connect Now", "A practical approach to business management systems", "CompanyFlow plans, builds and supports business management systems around your goals. We focus on dependable delivery, clear milestones and measurable business outcomes—not unnecessary complexity.", ("Business-focused delivery", "Reliable ongoing support"), [("Strategy & Planning", "We define goals, scope and a realistic roadmap before implementation."), ("Custom Implementation", "A solution shaped around your workflows, systems and customers."), ("Quality & Testing", "We check usability, performance and reliability before launch."), ("Continuous Improvement", "We help your solution evolve as your business grows.")], [("What is included in Business Management Systems?", "The scope is tailored to your goals and may include discovery, planning, implementation, testing and launch support."), ("Can this work with our existing systems?", "Yes. We review your current tools first and plan integrations where they add value.")], ("73+", 6)),
    "websites-landing-pages": ("Websites & Landing Pages", "Stunning websites that drive engagement. We combine thoughtful strategy, proven technology and clear communication to deliver a solution that fits the way your business works.", "Connect Now", "A practical approach to websites & landing pages", "CompanyFlow plans, builds and supports websites & landing pages around your goals. We focus on dependable delivery, clear milestones and measurable business outcomes—not unnecessary complexity.", ("Business-focused delivery", "Reliable ongoing support"), [("Strategy & Planning", "We define goals, scope and a realistic roadmap before implementation."), ("Custom Implementation", "A solution shaped around your workflows, systems and customers."), ("Quality & Testing", "We check usability, performance and reliability before launch."), ("Continuous Improvement", "We help your solution evolve as your business grows.")], [("What is included in Websites & Landing Pages?", "The scope is tailored to your goals and may include discovery, planning, implementation, testing and launch support."), ("Can this work with our existing systems?", "Yes. We review your current tools first and plan integrations where they add value.")], ("76+", 7)),
    "ai-automation": ("AI Automation", "Intelligent automation that streamlines your work. We combine thoughtful strategy, proven technology and clear communication to deliver a solution that fits the way your business works.", "Connect Now", "A practical approach to ai automation", "CompanyFlow plans, builds and supports ai automation around your goals. We focus on dependable delivery, clear milestones and measurable business outcomes—not unnecessary complexity.", ("Business-focused delivery", "Reliable ongoing support"), [("Strategy & Planning", "We define goals, scope and a realistic roadmap before implementation."), ("Custom Implementation", "A solution shaped around your workflows, systems and customers."), ("Quality & Testing", "We check usability, performance and reliability before launch."), ("Continuous Improvement", "We help your solution evolve as your business grows.")], [("What is included in AI Automation?", "The scope is tailored to your goals and may include discovery, planning, implementation, testing and launch support."), ("Can this work with our existing systems?", "Yes. We review your current tools first and plan integrations where they add value.")], ("79+", 8)),
    "mobile-web-apps": ("Mobile & Web Apps", "Customised mobile apps for every platform. We combine thoughtful strategy, proven technology and clear communication to deliver a solution that fits the way your business works.", "Connect Now", "A practical approach to mobile & web apps", "CompanyFlow plans, builds and supports mobile & web apps around your goals. We focus on dependable delivery, clear milestones and measurable business outcomes—not unnecessary complexity.", ("Business-focused delivery", "Reliable ongoing support"), [("Strategy & Planning", "We define goals, scope and a realistic roadmap before implementation."), ("Custom Implementation", "A solution shaped around your workflows, systems and customers."), ("Quality & Testing", "We check usability, performance and reliability before launch."), ("Continuous Improvement", "We help your solution evolve as your business grows.")], [("What is included in Mobile & Web Apps?", "The scope is tailored to your goals and may include discovery, planning, implementation, testing and launch support."), ("Can this work with our existing systems?", "Yes. We review your current tools first and plan integrations where they add value.")], ("82+", 9)),
    "ui-ux-product-design": ("UI/UX & Product Design", "Creating a unique identity for your business. We combine thoughtful strategy, proven technology and clear communication to deliver a solution that fits the way your business works.", "Connect Now", "A practical approach to ui/ux & product design", "CompanyFlow plans, builds and supports ui/ux & product design around your goals. We focus on dependable delivery, clear milestones and measurable business outcomes—not unnecessary complexity.", ("Business-focused delivery", "Reliable ongoing support"), [("Strategy & Planning", "We define goals, scope and a realistic roadmap before implementation."), ("Custom Implementation", "A solution shaped around your workflows, systems and customers."), ("Quality & Testing", "We check usability, performance and reliability before launch."), ("Continuous Improvement", "We help your solution evolve as your business grows.")], [("What is included in UI/UX & Product Design?", "The scope is tailored to your goals and may include discovery, planning, implementation, testing and launch support."), ("Can this work with our existing systems?", "Yes. We review your current tools first and plan integrations where they add value.")], ("85+", 5)),
    "ecommerce-development": ("Ecommerce Development", "Online stores built to sell and scale. We combine thoughtful strategy, proven technology and clear communication to deliver a solution that fits the way your business works.", "Connect Now", "A practical approach to ecommerce development", "CompanyFlow plans, builds and supports ecommerce development around your goals. We focus on dependable delivery, clear milestones and measurable business outcomes—not unnecessary complexity.", ("Business-focused delivery", "Reliable ongoing support"), [("Strategy & Planning", "We define goals, scope and a realistic roadmap before implementation."), ("Custom Implementation", "A solution shaped around your workflows, systems and customers."), ("Quality & Testing", "We check usability, performance and reliability before launch."), ("Continuous Improvement", "We help your solution evolve as your business grows.")], [("What is included in Ecommerce Development?", "The scope is tailored to your goals and may include discovery, planning, implementation, testing and launch support."), ("Can this work with our existing systems?", "Yes. We review your current tools first and plan integrations where they add value.")], ("88+", 6)),
    "conversion-focused-landing-pages": ("Conversion-Focused Landing Pages", "Landing pages designed to convert visitors. We combine thoughtful strategy, proven technology and clear communication to deliver a solution that fits the way your business works.", "Connect Now", "A practical approach to conversion-focused landing pages", "CompanyFlow plans, builds and supports conversion-focused landing pages around your goals. We focus on dependable delivery, clear milestones and measurable business outcomes—not unnecessary complexity.", ("Business-focused delivery", "Reliable ongoing support"), [("Strategy & Planning", "We define goals, scope and a realistic roadmap before implementation."), ("Custom Implementation", "A solution shaped around your workflows, systems and customers."), ("Quality & Testing", "We check usability, performance and reliability before launch."), ("Continuous Improvement", "We help your solution evolve as your business grows.")], [("What is included in Conversion-Focused Landing Pages?", "The scope is tailored to your goals and may include discovery, planning, implementation, testing and launch support."), ("Can this work with our existing systems?", "Yes. We review your current tools first and plan integrations where they add value.")], ("91+", 7)),
    "product-ui-ux": ("Product UI/UX", "Intuitive designs for user satisfaction. We combine thoughtful strategy, proven technology and clear communication to deliver a solution that fits the way your business works.", "Connect Now", "A practical approach to product ui/ux", "CompanyFlow plans, builds and supports product ui/ux around your goals. We focus on dependable delivery, clear milestones and measurable business outcomes—not unnecessary complexity.", ("Business-focused delivery", "Reliable ongoing support"), [("Strategy & Planning", "We define goals, scope and a realistic roadmap before implementation."), ("Custom Implementation", "A solution shaped around your workflows, systems and customers."), ("Quality & Testing", "We check usability, performance and reliability before launch."), ("Continuous Improvement", "We help your solution evolve as your business grows.")], [("What is included in Product UI/UX?", "The scope is tailored to your goals and may include discovery, planning, implementation, testing and launch support."), ("Can this work with our existing systems?", "Yes. We review your current tools first and plan integrations where they add value.")], ("94+", 8)),
    "creative-digital-experiences": ("Creative Digital Experiences", "Creative visuals to captivate your audience. We combine thoughtful strategy, proven technology and clear communication to deliver a solution that fits the way your business works.", "Connect Now", "A practical approach to creative digital experiences", "CompanyFlow plans, builds and supports creative digital experiences around your goals. We focus on dependable delivery, clear milestones and measurable business outcomes—not unnecessary complexity.", ("Business-focused delivery", "Reliable ongoing support"), [("Strategy & Planning", "We define goals, scope and a realistic roadmap before implementation."), ("Custom Implementation", "A solution shaped around your workflows, systems and customers."), ("Quality & Testing", "We check usability, performance and reliability before launch."), ("Continuous Improvement", "We help your solution evolve as your business grows.")], [("What is included in Creative Digital Experiences?", "The scope is tailored to your goals and may include discovery, planning, implementation, testing and launch support."), ("Can this work with our existing systems?", "Yes. We review your current tools first and plan integrations where they add value.")], ("97+", 9)),
    "lead-generation": ("Lead Generation", "Targeted campaigns for maximum reach. We combine thoughtful strategy, proven technology and clear communication to deliver a solution that fits the way your business works.", "Connect Now", "A practical approach to lead generation", "CompanyFlow plans, builds and supports lead generation around your goals. We focus on dependable delivery, clear milestones and measurable business outcomes—not unnecessary complexity.", ("Business-focused delivery", "Reliable ongoing support"), [("Strategy & Planning", "We define goals, scope and a realistic roadmap before implementation."), ("Custom Implementation", "A solution shaped around your workflows, systems and customers."), ("Quality & Testing", "We check usability, performance and reliability before launch."), ("Continuous Improvement", "We help your solution evolve as your business grows.")], [("What is included in Lead Generation?", "The scope is tailored to your goals and may include discovery, planning, implementation, testing and launch support."), ("Can this work with our existing systems?", "Yes. We review your current tools first and plan integrations where they add value.")], ("100+", 5)),
    "digital-growth": ("Digital Growth", "Grow your brand across digital channels. We combine thoughtful strategy, proven technology and clear communication to deliver a solution that fits the way your business works.", "Connect Now", "A practical approach to digital growth", "CompanyFlow plans, builds and supports digital growth around your goals. We focus on dependable delivery, clear milestones and measurable business outcomes—not unnecessary complexity.", ("Business-focused delivery", "Reliable ongoing support"), [("Strategy & Planning", "We define goals, scope and a realistic roadmap before implementation."), ("Custom Implementation", "A solution shaped around your workflows, systems and customers."), ("Quality & Testing", "We check usability, performance and reliability before launch."), ("Continuous Improvement", "We help your solution evolve as your business grows.")], [("What is included in Digital Growth?", "The scope is tailored to your goals and may include discovery, planning, implementation, testing and launch support."), ("Can this work with our existing systems?", "Yes. We review your current tools first and plan integrations where they add value.")], ("103+", 6)),
    "analytics-tracking": ("Analytics & Tracking", "Data insights for smarter decisions. We combine thoughtful strategy, proven technology and clear communication to deliver a solution that fits the way your business works.", "Connect Now", "A practical approach to analytics & tracking", "CompanyFlow plans, builds and supports analytics & tracking around your goals. We focus on dependable delivery, clear milestones and measurable business outcomes—not unnecessary complexity.", ("Business-focused delivery", "Reliable ongoing support"), [("Strategy & Planning", "We define goals, scope and a realistic roadmap before implementation."), ("Custom Implementation", "A solution shaped around your workflows, systems and customers."), ("Quality & Testing", "We check usability, performance and reliability before launch."), ("Continuous Improvement", "We help your solution evolve as your business grows.")], [("What is included in Analytics & Tracking?", "The scope is tailored to your goals and may include discovery, planning, implementation, testing and launch support."), ("Can this work with our existing systems?", "Yes. We review your current tools first and plan integrations where they add value.")], ("106+", 7)),
    "performance-marketing": ("Performance Marketing", "Strategic ads for higher conversions. We combine thoughtful strategy, proven technology and clear communication to deliver a solution that fits the way your business works.", "Connect Now", "A practical approach to performance marketing", "CompanyFlow plans, builds and supports performance marketing around your goals. We focus on dependable delivery, clear milestones and measurable business outcomes—not unnecessary complexity.", ("Business-focused delivery", "Reliable ongoing support"), [("Strategy & Planning", "We define goals, scope and a realistic roadmap before implementation."), ("Custom Implementation", "A solution shaped around your workflows, systems and customers."), ("Quality & Testing", "We check usability, performance and reliability before launch."), ("Continuous Improvement", "We help your solution evolve as your business grows.")], [("What is included in Performance Marketing?", "The scope is tailored to your goals and may include discovery, planning, implementation, testing and launch support."), ("Can this work with our existing systems?", "Yes. We review your current tools first and plan integrations where they add value.")], ("109+", 8)),
    "content-systems": ("Content Systems", "Content that keeps customers engaged. We combine thoughtful strategy, proven technology and clear communication to deliver a solution that fits the way your business works.", "Connect Now", "A practical approach to content systems", "CompanyFlow plans, builds and supports content systems around your goals. We focus on dependable delivery, clear milestones and measurable business outcomes—not unnecessary complexity.", ("Business-focused delivery", "Reliable ongoing support"), [("Strategy & Planning", "We define goals, scope and a realistic roadmap before implementation."), ("Custom Implementation", "A solution shaped around your workflows, systems and customers."), ("Quality & Testing", "We check usability, performance and reliability before launch."), ("Continuous Improvement", "We help your solution evolve as your business grows.")], [("What is included in Content Systems?", "The scope is tailored to your goals and may include discovery, planning, implementation, testing and launch support."), ("Can this work with our existing systems?", "Yes. We review your current tools first and plan integrations where they add value.")], ("112+", 9)),
    "workflow-automation": ("Workflow Automation", "Automate repetitive tasks to boost efficiency and accuracy. We combine thoughtful strategy, proven technology and clear communication to deliver a solution that fits the way your business works.", "Connect Now", "A practical approach to workflow automation", "CompanyFlow plans, builds and supports workflow automation around your goals. We focus on dependable delivery, clear milestones and measurable business outcomes—not unnecessary complexity.", ("Business-focused delivery", "Reliable ongoing support"), [("Strategy & Planning", "We define goals, scope and a realistic roadmap before implementation."), ("Custom Implementation", "A solution shaped around your workflows, systems and customers."), ("Quality & Testing", "We check usability, performance and reliability before launch."), ("Continuous Improvement", "We help your solution evolve as your business grows.")], [("What is included in Workflow Automation?", "The scope is tailored to your goals and may include discovery, planning, implementation, testing and launch support."), ("Can this work with our existing systems?", "Yes. We review your current tools first and plan integrations where they add value.")], ("115+", 5)),
    "ai-solutions": ("AI Solutions", "Enable systems to learn and improve with AI-driven algorithms. We combine thoughtful strategy, proven technology and clear communication to deliver a solution that fits the way your business works.", "Connect Now", "A practical approach to ai solutions", "CompanyFlow plans, builds and supports ai solutions around your goals. We focus on dependable delivery, clear milestones and measurable business outcomes—not unnecessary complexity.", ("Business-focused delivery", "Reliable ongoing support"), [("Strategy & Planning", "We define goals, scope and a realistic roadmap before implementation."), ("Custom Implementation", "A solution shaped around your workflows, systems and customers."), ("Quality & Testing", "We check usability, performance and reliability before launch."), ("Continuous Improvement", "We help your solution evolve as your business grows.")], [("What is included in AI Solutions?", "The scope is tailored to your goals and may include discovery, planning, implementation, testing and launch support."), ("Can this work with our existing systems?", "Yes. We review your current tools first and plan integrations where they add value.")], ("118+", 6)),
    "ai-sales-agents": ("AI Sales Agents", "Enhance customer interactions with intelligent virtual assistants. We combine thoughtful strategy, proven technology and clear communication to deliver a solution that fits the way your business works.", "Connect Now", "A practical approach to ai sales agents", "CompanyFlow plans, builds and supports ai sales agents around your goals. We focus on dependable delivery, clear milestones and measurable business outcomes—not unnecessary complexity.", ("Business-focused delivery", "Reliable ongoing support"), [("Strategy & Planning", "We define goals, scope and a realistic roadmap before implementation."), ("Custom Implementation", "A solution shaped around your workflows, systems and customers."), ("Quality & Testing", "We check usability, performance and reliability before launch."), ("Continuous Improvement", "We help your solution evolve as your business grows.")], [("What is included in AI Sales Agents?", "The scope is tailored to your goals and may include discovery, planning, implementation, testing and launch support."), ("Can this work with our existing systems?", "Yes. We review your current tools first and plan integrations where they add value.")], ("121+", 7)),
    "business-intelligence": ("Business Intelligence", "Extract valuable insights from complex data for better decisions. We combine thoughtful strategy, proven technology and clear communication to deliver a solution that fits the way your business works.", "Connect Now", "A practical approach to business intelligence", "CompanyFlow plans, builds and supports business intelligence around your goals. We focus on dependable delivery, clear milestones and measurable business outcomes—not unnecessary complexity.", ("Business-focused delivery", "Reliable ongoing support"), [("Strategy & Planning", "We define goals, scope and a realistic roadmap before implementation."), ("Custom Implementation", "A solution shaped around your workflows, systems and customers."), ("Quality & Testing", "We check usability, performance and reliability before launch."), ("Continuous Improvement", "We help your solution evolve as your business grows.")], [("What is included in Business Intelligence?", "The scope is tailored to your goals and may include discovery, planning, implementation, testing and launch support."), ("Can this work with our existing systems?", "Yes. We review your current tools first and plan integrations where they add value.")], ("124+", 8)),
    "secure-business-systems": ("Secure Business Systems", "Safeguard devices from cyber threats, malware and breaches. We combine thoughtful strategy, proven technology and clear communication to deliver a solution that fits the way your business works.", "Get a Quote", "A practical approach to secure business systems", "CompanyFlow plans, builds and supports secure business systems around your goals. We focus on dependable delivery, clear milestones and measurable business outcomes—not unnecessary complexity.", ("Business-focused delivery", "Reliable ongoing support"), [("Strategy & Planning", "We define goals, scope and a realistic roadmap before implementation."), ("Custom Implementation", "A solution shaped around your workflows, systems and customers."), ("Quality & Testing", "We check usability, performance and reliability before launch."), ("Continuous Improvement", "We help your solution evolve as your business grows.")], [("What is included in Secure Business Systems?", "The scope is tailored to your goals and may include discovery, planning, implementation, testing and launch support."), ("Can this work with our existing systems?", "Yes. We review your current tools first and plan integrations where they add value.")], ("127+", 9)),
    "cloud-infrastructure": ("Cloud Infrastructure", "Protect cloud data and systems with advanced security tools. We combine thoughtful strategy, proven technology and clear communication to deliver a solution that fits the way your business works.", "Get a Quote", "A practical approach to cloud infrastructure", "CompanyFlow plans, builds and supports cloud infrastructure around your goals. We focus on dependable delivery, clear milestones and measurable business outcomes—not unnecessary complexity.", ("Business-focused delivery", "Reliable ongoing support"), [("Strategy & Planning", "We define goals, scope and a realistic roadmap before implementation."), ("Custom Implementation", "A solution shaped around your workflows, systems and customers."), ("Quality & Testing", "We check usability, performance and reliability before launch."), ("Continuous Improvement", "We help your solution evolve as your business grows.")], [("What is included in Cloud Infrastructure?", "The scope is tailored to your goals and may include discovery, planning, implementation, testing and launch support."), ("Can this work with our existing systems?", "Yes. We review your current tools first and plan integrations where they add value.")], ("130+", 5)),
    "reliable-backups": ("Reliable Backups", "Ensure seamless recovery from unexpected data loss or attacks. We combine thoughtful strategy, proven technology and clear communication to deliver a solution that fits the way your business works.", "Get a Quote", "A practical approach to reliable backups", "CompanyFlow plans, builds and supports reliable backups around your goals. We focus on dependable delivery, clear milestones and measurable business outcomes—not unnecessary complexity.", ("Business-focused delivery", "Reliable ongoing support"), [("Strategy & Planning", "We define goals, scope and a realistic roadmap before implementation."), ("Custom Implementation", "A solution shaped around your workflows, systems and customers."), ("Quality & Testing", "We check usability, performance and reliability before launch."), ("Continuous Improvement", "We help your solution evolve as your business grows.")], [("What is included in Reliable Backups?", "The scope is tailored to your goals and may include discovery, planning, implementation, testing and launch support."), ("Can this work with our existing systems?", "Yes. We review your current tools first and plan integrations where they add value.")], ("133+", 6)),
    "authentication-access": ("Authentication & Access", "Strengthen identity protection with multi-layered access controls. We combine thoughtful strategy, proven technology and clear communication to deliver a solution that fits the way your business works.", "Get a Quote", "A practical approach to authentication & access", "CompanyFlow plans, builds and supports authentication & access around your goals. We focus on dependable delivery, clear milestones and measurable business outcomes—not unnecessary complexity.", ("Business-focused delivery", "Reliable ongoing support"), [("Strategy & Planning", "We define goals, scope and a realistic roadmap before implementation."), ("Custom Implementation", "A solution shaped around your workflows, systems and customers."), ("Quality & Testing", "We check usability, performance and reliability before launch."), ("Continuous Improvement", "We help your solution evolve as your business grows.")], [("What is included in Authentication & Access?", "The scope is tailored to your goals and may include discovery, planning, implementation, testing and launch support."), ("Can this work with our existing systems?", "Yes. We review your current tools first and plan integrations where they add value.")], ("136+", 7)),
    "application-hardening": ("Application Hardening", "Defend apps against vulnerabilities during and after deployment. We combine thoughtful strategy, proven technology and clear communication to deliver a solution that fits the way your business works.", "Get a Quote", "A practical approach to application hardening", "CompanyFlow plans, builds and supports application hardening around your goals. We focus on dependable delivery, clear milestones and measurable business outcomes—not unnecessary complexity.", ("Business-focused delivery", "Reliable ongoing support"), [("Strategy & Planning", "We define goals, scope and a realistic roadmap before implementation."), ("Custom Implementation", "A solution shaped around your workflows, systems and customers."), ("Quality & Testing", "We check usability, performance and reliability before launch."), ("Continuous Improvement", "We help your solution evolve as your business grows.")], [("What is included in Application Hardening?", "The scope is tailored to your goals and may include discovery, planning, implementation, testing and launch support."), ("Can this work with our existing systems?", "Yes. We review your current tools first and plan integrations where they add value.")], ("139+", 8)),
    "security-reviews": ("Security Reviews", "Analyze and enhance your organization's complete security framework. We combine thoughtful strategy, proven technology and clear communication to deliver a solution that fits the way your business works.", "Get a Quote", "A practical approach to security reviews", "CompanyFlow plans, builds and supports security reviews around your goals. We focus on dependable delivery, clear milestones and measurable business outcomes—not unnecessary complexity.", ("Business-focused delivery", "Reliable ongoing support"), [("Strategy & Planning", "We define goals, scope and a realistic roadmap before implementation."), ("Custom Implementation", "A solution shaped around your workflows, systems and customers."), ("Quality & Testing", "We check usability, performance and reliability before launch."), ("Continuous Improvement", "We help your solution evolve as your business grows.")], [("What is included in Security Reviews?", "The scope is tailored to your goals and may include discovery, planning, implementation, testing and launch support."), ("Can this work with our existing systems?", "Yes. We review your current tools first and plan integrations where they add value.")], ("142+", 9)),
    "website-content": ("Website Content", "Creating engaging and informative content. We combine thoughtful strategy, proven technology and clear communication to deliver a solution that fits the way your business works.", "Get a Quote", "A practical approach to website content", "CompanyFlow plans, builds and supports website content around your goals. We focus on dependable delivery, clear milestones and measurable business outcomes—not unnecessary complexity.", ("Business-focused delivery", "Reliable ongoing support"), [("Strategy & Planning", "We define goals, scope and a realistic roadmap before implementation."), ("Custom Implementation", "A solution shaped around your workflows, systems and customers."), ("Quality & Testing", "We check usability, performance and reliability before launch."), ("Continuous Improvement", "We help your solution evolve as your business grows.")], [("What is included in Website Content?", "The scope is tailored to your goals and may include discovery, planning, implementation, testing and launch support."), ("Can this work with our existing systems?", "Yes. We review your current tools first and plan integrations where they add value.")], ("145+", 5)),
    "seo": ("SEO", "Effective SEO strategies to increase traffic. We combine thoughtful strategy, proven technology and clear communication to deliver a solution that fits the way your business works.", "Get a Quote", "A practical approach to seo", "CompanyFlow plans, builds and supports seo around your goals. We focus on dependable delivery, clear milestones and measurable business outcomes—not unnecessary complexity.", ("Business-focused delivery", "Reliable ongoing support"), [("Strategy & Planning", "We define goals, scope and a realistic roadmap before implementation."), ("Custom Implementation", "A solution shaped around your workflows, systems and customers."), ("Quality & Testing", "We check usability, performance and reliability before launch."), ("Continuous Improvement", "We help your solution evolve as your business grows.")], [("What is included in SEO?", "The scope is tailored to your goals and may include discovery, planning, implementation, testing and launch support."), ("Can this work with our existing systems?", "Yes. We review your current tools first and plan integrations where they add value.")], ("148+", 6)),
    "documentation-training": ("Documentation & Training", "Learn and grow with expert-led training programs. We combine thoughtful strategy, proven technology and clear communication to deliver a solution that fits the way your business works.", "Get a Quote", "A practical approach to documentation & training", "CompanyFlow plans, builds and supports documentation & training around your goals. We focus on dependable delivery, clear milestones and measurable business outcomes—not unnecessary complexity.", ("Business-focused delivery", "Reliable ongoing support"), [("Strategy & Planning", "We define goals, scope and a realistic roadmap before implementation."), ("Custom Implementation", "A solution shaped around your workflows, systems and customers."), ("Quality & Testing", "We check usability, performance and reliability before launch."), ("Continuous Improvement", "We help your solution evolve as your business grows.")], [("What is included in Documentation & Training?", "The scope is tailored to your goals and may include discovery, planning, implementation, testing and launch support."), ("Can this work with our existing systems?", "Yes. We review your current tools first and plan integrations where they add value.")], ("151+", 7)),
    "domain-hosting": ("Domain & Hosting", "Trusted hosting for your online presence. We combine thoughtful strategy, proven technology and clear communication to deliver a solution that fits the way your business works.", "Get a Quote", "A practical approach to domain & hosting", "CompanyFlow plans, builds and supports domain & hosting around your goals. We focus on dependable delivery, clear milestones and measurable business outcomes—not unnecessary complexity.", ("Business-focused delivery", "Reliable ongoing support"), [("Strategy & Planning", "We define goals, scope and a realistic roadmap before implementation."), ("Custom Implementation", "A solution shaped around your workflows, systems and customers."), ("Quality & Testing", "We check usability, performance and reliability before launch."), ("Continuous Improvement", "We help your solution evolve as your business grows.")], [("What is included in Domain & Hosting?", "The scope is tailored to your goals and may include discovery, planning, implementation, testing and launch support."), ("Can this work with our existing systems?", "Yes. We review your current tools first and plan integrations where they add value.")], ("154+", 8)),
    "technical-documentation": ("Technical Documentation", "Boost credibility with clear technical documentation. We combine thoughtful strategy, proven technology and clear communication to deliver a solution that fits the way your business works.", "Get a Quote", "A practical approach to technical documentation", "CompanyFlow plans, builds and supports technical documentation around your goals. We focus on dependable delivery, clear milestones and measurable business outcomes—not unnecessary complexity.", ("Business-focused delivery", "Reliable ongoing support"), [("Strategy & Planning", "We define goals, scope and a realistic roadmap before implementation."), ("Custom Implementation", "A solution shaped around your workflows, systems and customers."), ("Quality & Testing", "We check usability, performance and reliability before launch."), ("Continuous Improvement", "We help your solution evolve as your business grows.")], [("What is included in Technical Documentation?", "The scope is tailored to your goals and may include discovery, planning, implementation, testing and launch support."), ("Can this work with our existing systems?", "Yes. We review your current tools first and plan integrations where they add value.")], ("157+", 9)),
}

ENGAGE = {
"staff-augmentation": dict(
 h1="Extend Your Team with Skilled Specialists", hero="Add experienced developers and technology professionals to your team without the overhead of traditional hiring.", cta="Talk to Our Team", adv_h="Flexible Talent, Built Around Your Goals", adv_p="Bring in the right expertise when you need it, with transparent communication and a delivery-focused approach.", benefits=[("Cost Effective","Pay for the expertise and time you need."),("Faster Hiring","Add capable specialists without a long recruitment cycle."),("Quality Assurance","Work with experienced professionals and clear standards."),("Clear Communication","Stay aligned with regular updates and direct collaboration."),("Flexible Capacity","Scale support as priorities and workloads change."),("Specialist Skills","Access a broad range of technical experience.")], form_h="Build Your Extended Team", form_p="Tell us which skills you need and we will discuss a practical staffing plan."),
"project-base": dict(
 h1="Deliver Your Next Project with Confidence", hero="From discovery to launch, our project-based delivery gives you a clear scope, accountable execution and dependable results.", cta="Discuss Your Project", adv_h="A Clear Path from Idea to Delivery", adv_p="We organise each engagement around agreed outcomes, transparent milestones and quality checks throughout delivery.", benefits=[("Defined Scope","Agree on deliverables and priorities before work begins."),("Milestone Delivery","Track progress through clear stages and reviews."),("Quality Assurance","Test the work before handover."),("Single Point of Contact","Keep decisions and communication organised."),("Transparent Progress","Know what is happening and what comes next."),("Right-Fit Team","Bring together the specialists your project requires.")], form_h="Tell Us About Your Project", form_p="Share your goals, requirements and timeline. We will help shape the next steps."),
}
