const { createClient } = window.supabase;
const cfg = window.COMPANYFLOW_SUPABASE || {};
const supabaseClient = createClient(cfg.url, cfg.publishableKey);
const app = document.getElementById("app");
const seedCategories = ["Real Estate","Business Software","Healthcare","E-commerce & Retail","AI & Automation","Travel & Transportation"];
const seedProjects = [
  ["CompanyFlow","Business Software"],["LabStacks","Healthcare"],["Aurum Accessories","E-commerce & Retail"],
  ["AgentHub","AI & Automation"],["AI Sales Agent","AI & Automation"],["Destino Travels","Travel & Transportation"],
  ["Real Estate Website","Real Estate"],["Property Management Platform","Real Estate"]
];
let session = null;
let db = {categories:[],projects:[],home:{heroTitle:"Digital products built around your business.",heroText:"Websites, ecommerce, custom software and AI automation built around the way your business works.",years:"10+",projects:"500+",clients:"100%"},animations:{hero:"fadeUp",projects:"fadeUp",duration:800,stagger:120}};

function esc(s){return String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]))}
function setMode(t,ok=true){document.getElementById("mode").textContent=t;document.querySelector(".status i").style.opacity=ok?"1":".45"}
function authScreen(message=""){app.innerHTML=`<div class="card auth-card"><h2>CompanyFlow Admin</h2><p class="muted">Sign in to manage the live CompanyFlow CMS.</p><form class="form" id="authForm"><div class="field"><label>Email</label><input id="ae" type="email" required autocomplete="email"></div><div class="field"><label>Password</label><input id="apw" type="password" required autocomplete="current-password"></div><div><button class="btn primary" type="submit">Sign in</button> <button class="btn" type="button" id="signup">Create account</button></div><p class="muted" id="authMsg">${esc(message)}</p></form></div>`;
document.getElementById("authForm").onsubmit=async e=>{e.preventDefault();const {error}=await supabaseClient.auth.signInWithPassword({email:ae.value,password:apw.value});if(error)authScreen(error.message);else await boot()};
document.getElementById("signup").onclick=async()=>{const {data,error}=await supabaseClient.auth.signUp({email:ae.value,password:apw.value});document.getElementById("authMsg").textContent=error?error.message:(data.session?"Account created.":"Account created. Check your email if confirmation is enabled.")};
}
async function isAdmin(){if(!session?.user)return false;const {data}=await supabaseClient.from("companyflow_admins").select("user_id").eq("user_id",session.user.id).maybeSingle();return !!data}
async function bootstrapAdmin(){const {data}=await supabaseClient.from("companyflow_admins").select("user_id",{count:"exact"});if((data||[]).length===0){await supabaseClient.from("companyflow_admins").insert({user_id:session.user.id})}}
async function load(){
const [c,p,h,a]=await Promise.all([
supabaseClient.from("companyflow_categories").select("*").order("sort_order"),
supabaseClient.from("companyflow_projects").select("*, companyflow_categories(name)").order("sort_order"),
supabaseClient.from("companyflow_site_content").select("*"),
supabaseClient.from("companyflow_animation_settings").select("*")
]);
if(c.error||p.error||h.error||a.error)throw new Error(c.error?.message||p.error?.message||h.error?.message||a.error?.message);
db.categories=c.data||[];db.projects=(p.data||[]).map(x=>({...x,category:x.companyflow_categories?.name||""}));
const hv=(h.data||[]).find(x=>x.key==="homepage")?.value;if(hv)db.home={...db.home,...hv};
const av=(a.data||[]).find(x=>x.key==="global")?.value;if(av)db.animations={...db.animations,...av};
}
async function seed(){
const {count}=await supabaseClient.from("companyflow_categories").select("*",{count:"exact",head:true});
if(!count){const {data:cats,error}=await supabaseClient.from("companyflow_categories").insert(seedCategories.map((name,i)=>({name,slug:name.toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,""),sort_order:i}))).select();if(error)throw error;
const by=Object.fromEntries((cats||[]).map(x=>[x.name,x.id]));
await supabaseClient.from("companyflow_projects").insert(seedProjects.map((x,i)=>({name:x[0],slug:x[0].toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,""),category_id:by[x[1]],description:"",image_url:"",published:true,sort_order:i})));
await supabaseClient.from("companyflow_site_content").upsert({key:"homepage",value:db.home});
await supabaseClient.from("companyflow_animation_settings").upsert({key:"global",value:db.animations});
}
}
async function boot(){session=(await supabaseClient.auth.getSession()).data.session;if(!session){setMode("Sign in required",false);return authScreen()}await bootstrapAdmin();if(!(await isAdmin())){await supabaseClient.auth.signOut();return authScreen("This account is not an admin.")}try{await seed();await load();setMode("Live Supabase CMS");render("dashboard")}catch(e){setMode("Database error",false);authScreen(e.message)}}
function render(v="dashboard"){document.querySelectorAll(".nav").forEach(x=>x.classList.toggle("active",x.dataset.view===v));document.getElementById("title").textContent=v[0].toUpperCase()+v.slice(1);({dashboard,projects,categories,homepage,animations}[v]||dashboard)()}
function dashboard(){app.innerHTML=`<div class="grid"><div class="card"><div class="metric">${db.projects.length}</div><p class="muted">Projects</p></div><div class="card"><div class="metric">${db.categories.length}</div><p class="muted">Categories</p></div><div class="card"><div class="metric">${db.projects.filter(x=>x.published).length}</div><p class="muted">Published</p></div></div><div class="card" style="margin-top:18px"><h3>Live CMS</h3><p class="muted">Changes are stored in Supabase and can be consumed by the public CompanyFlow frontend.</p><button class="btn" onclick="logout()">Sign out</button></div>`}
function projects(){app.innerHTML=`<div class="toolbar"><span class="muted">${db.projects.length} projects</span><button class="btn primary" onclick="editProject()">+ Add Project</button></div><table class="table"><thead><tr><th>Project</th><th>Category</th><th>Status</th><th></th></tr></thead><tbody>${db.projects.map(p=>`<tr><td><strong>${esc(p.name)}</strong></td><td>${esc(p.category)}</td><td>${p.published?"Published":"Draft"}</td><td class="actions"><button class="btn" onclick="editProject('${p.id}')">Edit</button><button class="btn danger" onclick="removeProject('${p.id}')">Delete</button></td></tr>`).join("")}</tbody></table>`}
function editProject(id){const p=id?db.projects.find(x=>x.id===id):{name:"",category:db.categories[0]?.name||"",description:"",image_url:"",published:true};app.innerHTML=`<div class="card"><form class="form" onsubmit="event.preventDefault();saveProject('${id||""}')"><div class="row"><div class="field"><label>Project name</label><input id="pn" value="${esc(p.name)}" required></div><div class="field"><label>Category</label><select id="pc">${db.categories.map(c=>`<option value="${esc(c.name)}" ${c.name===p.category?"selected":""}>${esc(c.name)}</option>`).join("")}</select></div></div><div class="field"><label>Description</label><textarea id="pd">${esc(p.description)}</textarea></div><div class="row"><div class="field"><label>Image URL</label><input id="pi" value="${esc(p.image_url||p.image||"")}"></div><div class="field"><label>Status</label><select id="pp"><option value="1" ${p.published?"selected":""}>Published</option><option value="0" ${!p.published?"selected":""}>Draft</option></select></div></div><div><button class="btn primary">Save Project</button> <button type="button" class="btn" onclick="render('projects')">Cancel</button></div></form></div>`}
async function saveProject(id){const category=db.categories.find(c=>c.name===pc.value);const payload={name:pn.value,slug:(id?db.projects.find(x=>x.id===id).slug:pn.value).toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,""),category_id:category?.id||null,description:pd.value,image_url:pi.value,published:pp.value==="1",updated_at:new Date().toISOString()};const q=id?supabaseClient.from("companyflow_projects").update(payload).eq("id",id):supabaseClient.from("companyflow_projects").insert(payload);const {error}=await q;if(error)return alert(error.message);await load();render("projects")}
async function removeProject(id){if(confirm("Delete this project?")){const {error}=await supabaseClient.from("companyflow_projects").delete().eq("id",id);if(error)alert(error.message);else{await load();projects()}}}
function categories(){app.innerHTML=`<div class="toolbar"><span class="muted">Manage project categories</span><button class="btn primary" onclick="addCategory()">+ Add Category</button></div><div class="grid">${db.categories.map(c=>`<div class="card"><h3>${esc(c.name)}</h3><p class="muted">${db.projects.filter(p=>p.category===c.name).length} projects</p><button class="btn danger" onclick="removeCategory('${c.id}')">Delete</button></div>`).join("")}</div>`}
async function addCategory(){const n=prompt("Category name");if(!n)return;const {error}=await supabaseClient.from("companyflow_categories").insert({name:n,slug:n.toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,""),sort_order:db.categories.length});if(error)alert(error.message);else{await load();categories()}}
async function removeCategory(id){if(db.projects.some(p=>p.category===db.categories.find(c=>c.id===id)?.name))return alert("Move/delete its projects first.");const {error}=await supabaseClient.from("companyflow_categories").delete().eq("id",id);if(error)alert(error.message);else{await load();categories()}}
function homepage(){const h=db.home;app.innerHTML=`<div class="card"><form class="form" onsubmit="event.preventDefault();saveHome()"><div class="field"><label>Hero title</label><input id="ht" value="${esc(h.heroTitle)}"></div><div class="field"><label>Hero text</label><textarea id="hx">${esc(h.heroText)}</textarea></div><div class="row"><div class="field"><label>Years</label><input id="hy" value="${esc(h.years)}"></div><div class="field"><label>Projects delivered</label><input id="hp" value="${esc(h.projects)}"></div></div><div class="field"><label>Happy clients</label><input id="hc" value="${esc(h.clients)}"></div><button class="btn primary">Save Homepage</button></form></div>`}
async function saveHome(){db.home={heroTitle:ht.value,heroText:hx.value,years:hy.value,projects:hp.value,clients:hc.value};const {error}=await supabaseClient.from("companyflow_site_content").upsert({key:"homepage",value:db.home,updated_at:new Date().toISOString()});if(error)alert(error.message);else alert("Homepage saved.");}
function animations(){app.innerHTML=`<div class="card"><h3>Live animation preview</h3><p class="muted">Preview and store the animation settings used by CompanyFlow.</p><div class="anim-controls"><button class="pill active" onclick="setAnim('fadeUp',this)">Fade Up</button><button class="pill" onclick="setAnim('fade',this)">Fade</button><button class="pill" onclick="setAnim('zoom',this)">Zoom</button><button class="pill" onclick="setAnim('slide',this)">Slide</button></div><div class="row"><div class="field"><label>Duration (ms)</label><input id="ad" type="number" value="${db.animations.duration}" onchange="saveAnimations()"></div><div class="field"><label>Stagger (ms)</label><input id="as" type="number" value="${db.animations.stagger}" onchange="saveAnimations()"></div></div><div class="preview"><h2 class="preview-title anim fadeUp" id="ap">CompanyFlow</h2><div class="preview-card anim fadeUp" id="ac">Project card</div></div></div>`}
async function saveAnimations(){db.animations.duration=+ad.value;db.animations.stagger=+as.value;await supabaseClient.from("companyflow_animation_settings").upsert({key:"global",value:db.animations,updated_at:new Date().toISOString()})}
function setAnim(a,b){db.animations.hero=a;document.querySelectorAll(".pill").forEach(x=>x.classList.remove("active"));b.classList.add("active");const t=document.getElementById("ap"),c=document.getElementById("ac");t.className="preview-title anim "+a;c.className="preview-card anim "+a;t.style.animationDuration=db.animations.duration+"ms";c.style.animationDuration=db.animations.duration+"ms";saveAnimations()}
async function logout(){await supabaseClient.auth.signOut();session=null;setMode("Sign in required",false);authScreen()}
document.querySelectorAll(".nav").forEach(n=>n.onclick=()=>render(n.dataset.view));
supabaseClient.auth.onAuthStateChange((_e,s)=>{session=s});
boot();