-- CompanyFlow CMS schema for Supabase
create table if not exists public.categories (
 id bigint generated by default as identity primary key,
 name text not null unique,
 slug text not null unique,
 sort_order integer not null default 0,
 created_at timestamptz not null default now()
);
create table if not exists public.projects (
 id bigint generated by default as identity primary key,
 name text not null,
 slug text not null unique,
 category_id bigint references public.categories(id) on delete restrict,
 description text default '',
 image_url text default '',
 project_url text default '',
 github_url text default '',
 technologies jsonb not null default '[]'::jsonb,
 features jsonb not null default '[]'::jsonb,
 published boolean not null default true,
 featured boolean not null default false,
 sort_order integer not null default 0,
 created_at timestamptz not null default now(),
 updated_at timestamptz not null default now()
);
create table if not exists public.site_content (
 id bigint generated by default as identity primary key,
 key text not null unique,
 value jsonb not null default '{}'::jsonb,
 updated_at timestamptz not null default now()
);
create table if not exists public.animation_settings (
 id bigint generated by default as identity primary key,
 key text not null unique,
 value jsonb not null default '{}'::jsonb,
 updated_at timestamptz not null default now()
);
alter table public.categories enable row level security;
alter table public.projects enable row level security;
alter table public.site_content enable row level security;
alter table public.animation_settings enable row level security;
-- Add authenticated-admin policies after authentication is connected.
